### ISSUE TITLE
Run on R 4.02

### ISSUE THREAD

**Issue by harryahlas** [TommyJones/tidylda#46]
I cannot install this using R 4.02. is there a way you can make this package available on cran for that version? Asking for a friend.

**Comment by TommyJones** [comment]
tidylda is not yet ready for CRAN. It violates one of CRAN's policies about multithreading. I'll get that sorted once I can carve out time. Even so, a package this involved might take 2 months to get on CRAN once I submit since CRAN does lots of checks for new package submissions. 

The version on GitHub now should work so long as you don't set any `threads` argument greater than 1, the default.

Is the issue that your friend cannot install it at all using `remotes::install_github("tommyjones/tidylda")`? Or are they trying to use `install.packages()`, which just checks CRAN?

**Comment by harryahlas** [comment]
Ah ok. Yes it is from an environment that needs to use install.packages(). We will figure out a work around. Thanks. Btw this package is great.

**Comment by TommyJones** [comment]
Thanks. I intend to have it on CRAN this year. Feel free to open an issue if you encounter any future problems.
