### ISSUE TITLE
JOSS Review: Paper review comments 

### ISSUE THREAD

**Issue by hassaniazi** [TommyJones/tidylda#75]
## Review for Latent Dirichlet Allocation Using ‘tidyverse’ Conventions
This [paper](https://github.com/TommyJones/tidylda/blob/main/tidylda-joss/paper.md) describes the implementation of LDA using tidyverse ecosystem to improve user-friendliness and give more control over complex data wrangling. Doing so has enabled new capabilities e.g., non-uniform initializations or setting flexible priors for LDA. Thanks for providing sample data and guidance  for users on how to run to explore the model's functionality. I was able to execute tidy functions (print, glance, augment etc) and reproduce the results and plots from [README.md](https://github.com/TommyJones/tidylda/blob/main/README.md), good job! 

#### General comments:
I have two overall comments and then some specific comments: 

1. Analytical contributions 
It is unclear from the paper if any analytical adjustments to the LDA formulation have been made or if the "novel features" are mostly in the code base to improve the workflow. Initialization from prior Dirichlet or tLDA seem to qualify as analytical modifications that warrant to be highlighted further (e.g., explained in text and supported by an equation) for clarity and visibility. 

2. Paper writing 
More work needs to go into giving it the paper a more cogent and incisive shape. Part of the summary and some other bits read as a book/dissertation chapter. Transforming the background theory and focusing more on the contributions of this work could be one way to respond. For instance, taking the second para of the summary as an example, I’d recommend adapting the summary to highlight your contributions rather than the summary of tidyverse, which is well established and isn’t the main contribution of this work. Reference to "described in Chapter 5" in line 71 also needs to be removed. To be clear, I am not referring to the very useful _Latent Dirichlet Allocation and Notation_ and _Transfer LDA (tLDA)_  sections and not recommending a full rewrite-up of the paper, just minor but intentional adjustments would suffice. 

### Specific comments: 

- Line 04 – Affiliation: do you want to specify which foundation? 
- Line 18 – just a minor reference formatting comment: Is the reference for Silge et al. missing? If it is referring to Silge and Robinson then it would Silge and Robinson (2016) not Silge et al
- Line 22 – can you add a few words about “broom style” for the readers who might not be familiar with it
- Line 30 – can you add a few examples of other comparable packages?
- Line 69 – A few words introducing the Gibbs sampler and its specific use in tidylda would improve the clarity of the manuscript
- Line 71 – Reference to "described in Chapter 5" needs to be removed.
- Line 74 – Do you mean single discrete values? If not can you clarify the difference between scalar and vector in the context of its usage for tidylda? 
- Line 77 – If tLDA is one of the unique contributions of this work then this should be highlighted in the text. Currently, it is not clear. 
- Line 80 – Again, it'd be useful to spell out other implementations somewhere in the text.
- Line 107 – Are the arguments in Dirichlet(𝐶𝑣𝑘 + 𝜂𝑘) and Dirichlet(𝐶𝑣𝑘 + 𝜂𝑘) for tLDA meant to be the same?

Review repo: https://github.com/openjournals/joss-reviews/issues/6800

**Comment by TommyJones** [comment]
Hello. Thank you again for the review. I'll structure my response/actions based on your comments above. I've included a checklist for me at the bottom to take care of these issues. But I do have a need for more guidance as it relates to 1 & 2, below.

### General Comments

1. I'm confused. Lines 49 - 60 of the paper cover the mathematical modification of LDA. Lines 61 - 115 cover the computational aspects. I also cited the dissertation upon which the package is based (Jones, 2023). So can I ask for specific recommendations on what needs clarification here?
2. I will remove any accidental references to my dissertation (e.g. "chapter 5"). 
    I'm not sure what you mean by giving the paper "a more cogent and incisive shape." I'm again confused as it seems like I have conflicting guidance here. You say "Transforming the background theory and focusing more on the contributions of this work could be one way to respond" but then also say "I am not referring to the very useful Latent Dirichlet Allocation and Notation and Transfer LDA (tLDA) sections." But implementing tLDA is one of the fundamental intellectual contributions here. (I am working on getting a stand alone tLDA paper published in a more appropriate journal as it's outside of the scope of JOSS.) Forgive me; I am not trying to be difficult. I genuinely don't know what I'm being asked to do. 

### Specific Comments
* Line 04 – The company is named Foundation. 
* Line 18 – I will update to say Silge and Robinson.
* Line 22 – I will add a few words about “broom style” for the readers who might not be familiar with it
* Line 30 – I will add a paragraph about topic modeling packages in R and OSS in general.
* Line 69 – I will add a few sentences on Gibbs sampling as an introduction.
* Line 71 – I will remove any reference to "described in Chapter 5" or similar.
* Line 74 – I am reluctant to make this change. Maybe it's my math background, but "scalar" has a precise meaning. i.e., a number.
* Line 77 – This seems like it relates to 1 & 2, above. I will wait on your response before addressing this.
* Line 80 – I will add a paragraph about topic modeling packages in R and OSS in general.
* Line 107 – They are nearly the same. There is a subscript on eta in the latter because it refers to tLDA. There is no subscript on eta in the former because it refers to vanilla LDA. 


### Checklist
- [ ] Clarify intellectual contribution (awaiting guidance)
- [ ] Line 18 - say "Silge and Robinson"
- [ ] Line 22 - describe the broom package in one sentence
- [ ] Add a paragraph about LDA implementations in R and OSS in general
- [ ] Line 69 - describe Gibbs sampling
- [ ] Remove any references to "chapter 5" or similar on line 71 and throughout the paper

**Comment by TommyJones** [comment]
Side note: I know Julia and Dave. I feel pretty bad about relegating Dave to an "et al." 😅 Sorry, Dave.

**Comment by TommyJones** [comment]
Issues except for clarifying contribution are taken care of over several commits ending with d04f62177528b165910b01fe4ad8535b92857e7c

**Comment by hassaniazi** [comment]
Thanks for resolving most of my comments. 

1. I wasn't sure if the modifications are novel to this work or have been presented before. In my understanding, these are novel to this. I believe including a phrase like the following should be sufficient: "In this work, we introduce transfer LDA (tLDA), which modifies LDA in the following way:"

2. This comment of mine has also been addressed with your changes through out the manuscript and by creating a new section on topic modeling in R. I was mainly looking for a clear distinction between background and your contributions, which the new paper separates well. 

Congratulations on this work.

**Comment by TommyJones** [comment]
Awesome. Thank you for taking the time and effort to go through the paper and code. Onward!

Sent with Shortwave <https://www.shortwave.com?utm_medium=email&utm_content=signature&utm_source=am9uZXMudGhvcy53QGdtYWlsLmNvbQ==>
